#!/usr/bin/env bash
#task to use case
n=1;
while [ $n -le 20 ]; do
		printf "%s\n" "$n"
		(( n++ ))

case $n in
5)
	printf "%s\n"	"bad luck from China"
	;;
10)
	        printf "%s\n" "bad luck from Japan"
		        ;;
18)
			printf "%s\n" "bad luck from Italy"					                        ;;
esac
done
