#!/usr/bin/env bash
#task to display hour and minutes
Hour=0;
while [ $Hour -le 12 ]; do
		printf "%s\n" "Hour: $Hour"
		minute=1;
		while [ $minute -le 59 ]; do 
			printf "%s\n" "$minute"
			(( minute ++))
		done
		(( Hour++ ))
	done
