#!/usr/bin/env bash
#task whit if and file test operators
archive="./school"
if [ -e "$archive" ]
then
	echo school file exists
	if [ -s "$archive" ]
	then
		echo school file is not empty
	
		if [ -f "$archive" ]
		then
			echo school is a regular file
		
		fi
		
	else
	       	echo school file is empty
	fi
else
	echo school file does not exist
fi
