#!/usr/bin/env bash
#A Bash script that use different trap´s.
touch /var/run/myscript.pid

trap "echo I hate the kill command; rm -f /var/run/myscript.pid; exit" 15
trap "echo Y U no love me?!" 2
trap "rm -f /var/run/myscript.pid" 3
while :
do
		echo To infinity and beyond
			sleep 2
done
