#!/usr/bin/env bash
#A Bash init script 
if [[ $1 == start ]]
then
	touch /var/run/my_process.pid
	./manage_my_process &
	export aux=$!
	echo "$aux" > /var/run/my_process.pid
	echo manage_my_process started
elif [[ $1 == stop ]]
then
	kill -9 "$(cat /var/run/my_process.pid)"
	echo manage_my_process stopped
	rm /var/run/my_process.pid
elif [[ $1 == restart ]]
then
	kill -9 "$(cat /var/run/my_process.pid)"
	echo manage_my_process restarted
	rm /var/run/my_process.pid
	touch /var/run/my_process.pid
        ./manage_my_process &
	echo $! > /var/run/my_process.pid
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
